apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.volumeClaimName}}
  labels:
    app: {{.Values.app}}
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.volumeStorage}}
