apiVersion: v1
kind: Secret
metadata:
  name: secret
data:
  username: {{.Values.data.username}}
  password: {{.Values.data.password}}
  url: J2pkYmM6bXlzcWw6Ly9teXNxbDozMzA2L2VtcGxveWVlX21hbmFnZW1lbnRfc3lzdGVtP3VzZVNTTD1mYWxzZSZzZXJ2ZXJUaW1lem9uZT1VVEMmdXNlTGVnYWN5RGF0ZXRpbWVDb2RlPWZhbHNlJw==
