apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: assignment-deployment
spec:
  selector:
    matchLabels:
      app: assignment-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: assignment-demo
    spec:
      containers:
        - name: assignment
          image: unnati2409/assignment-repo:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_HOST
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: host
            - name: SPRING_DATASOURCE_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: dbName
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: password
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: url
