apiVersion: v1
kind: Service
metadata:
  name: {{.Values.serviceName}}
spec:
  selector:
    app: {{.Values.app}}
  ports:
    - name: http
      protocol: "TCP"
      port: {{.Values.containerPort}}
      targetPort: {{.Values.containerPort}}
  type: NodePort
