apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Values.ingressName}}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{.Values.ingressHost}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{.Values.serviceName}}
                port:
                  number: {{.Values.containerPort}}
