app:
  name: qa-mysql
  container:
    - image: mysql:5.7
      args:
        - "--ignore-db-dir=lost+found"
      name: qa-mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: qa-mysql-root-pass
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: qa-mysql-db-url
              key: database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: qa-mysql-user-pass
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: qa-mysql-user-pass
              key: password
  ports:
    - containerPort: 3307
      name: qa-mysql
